### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by katarinabrilej** [timkalan/APPR-2019-20#2]
Če želiš v ponedeljek predstavljati projekt, prosim poskrbi, da boš imel delujoče poročilo. Meni trenutno javi error, če ga želim zagnati preko Binderja. Morda je razlog v tem, ker uporabljaš knjižnico `StandardizeText`, ki pa mislim, da je ni v naprej pripravljeni sliki [Docker](https://www.docker.com/). Za sprotno namestitev poskrbiš tako, da jo v datoteki [`install.R`](install.R) namestiš z ukazom `install.packages`.

**Comment by jaanos** [comment]
S knjižnico `StandardizeText` se poročilo pri meni prevede, tako da sem dodal povezavo na repozitorij za zagovore. Vseeno pa svetujem, da poročilo še nekoliko urediš - ko boš imel pripravljeno različico za predstavitev, javi, da posodobim povezavo.

Dal sem delat novo sliko za Docker, ki bo vsebovala knjižnico `StandardizeText`, tako da bi morala biti pripravljena čez približno dve uri (poganjanje Binderja s trenutnim commitom bo sicer vzelo že pripravljeno sliko, tako da bo potrebno narediti nov commit, morda tudi posodobiti `Dockerfile`). Da bi sicer nameščanje z `install.R` delovalo, ukaz `install.packages` seveda ne sme biti zakomentiran (trenutno si namreč le dopolnil zakomentiran primer). Seveda pa z novo sliko to ne bo več potrebno, tako da ti te datoteke ni treba spreminjati.
